Repository econominhas/backend, pull requests merged in 2024-02, with the labels that each got.

#6 Partially add salary
  README.md
  prisma/migrations/20240219013610_refact_salary/migration.sql
  prisma/schema.prisma
  src/models/account.ts
  src/models/salary.ts
  src/repositories/postgres/account/account-repository.service.ts
  src/types/enums/rt-template.ts
  src/usecases/account/account.service.ts
  src/usecases/salary/salary.module.ts
  src/usecases/salary/salary.service.ts
Labels: feature

#28 chore: add validation on localstack/buckets.sh
  localstack/buckets.sh
Labels: other

#33 fix: resolve docker network issue
  docker-compose.yml
Labels: bugfix
